const songs = {
    "credits": {
        "music": "audio/Credits.mp3",
        "artist": "Frums",
        "name": "Credits",
        "leaderboards": [
            13801,
            13802,
            13804
        ],
        "chart": [
            {"time": 0, "pos": [0, 0]},
            {"time": 1, "pos": [128, 128]},
            {"time": 1e100, "pos": [0, 0]}
        ]
    },
    "KATAMARI": {
        "music": "audio/Femtanyl - KATAMARI.mp3",
        "artist": "Femtanyl",
        "name": "KATAMARI",
        "art": "img/Femtanyl - KATAMARI.png",
        "link": "https://www.newgrounds.com/audio/listen/1264675",
        "leaderboards": [
            13847, //score
            13846, //combo
            13845  //acc
        ],
        "chart": [
            {"time": 0, "pos": [64, 64]},
            {"time": 1.4, "pos": [320, 64]},
            {"time": 1.4, "pos": [64, 64]},
            {"time": 2.8, "pos": [320, 64]},
            {"time": 2.8, "pos": [64, 320]},
            {"time": 4.2, "pos": [320, 320]},
            {"time": 4.2, "pos": [64, 320]},
            {"time": 5.6, "pos": [320, 320]},
            {"time": 5.6, "pos": [64, 64]},
            {"time": 7, "pos": [320, 64]},
            {"time": 7, "pos": [64, 64]},
            {"time": 8.4, "pos": [320, 64]},
            {"time": 8.4, "pos": [64, 320]},
            {"time": 9.8, "pos": [320, 320]},
            {"time": 9.8, "pos": [64, 320]},
            {"time": 11.2, "pos": [320, 320]},
            {"time": (11.2*1)+0, "pos": [64, 64]},
            {"time": (11.2*1)+1.4, "pos": [320, 64]},
            {"time": (11.2*1)+1.4, "pos": [64, 64]},
            {"time": (11.2*1)+2.8, "pos": [320, 64]},
            {"time": (11.2*1)+2.8, "pos": [64, 320]},
            {"time": (11.2*1)+4.2, "pos": [320, 320]},
            {"time": (11.2*1)+4.2, "pos": [64, 320]},
            {"time": (11.2*1)+5.6, "pos": [320, 320]},
            {"time": (11.2*1)+5.6, "pos": [64, 64]},
            {"time": (11.2*1)+7, "pos": [320, 64]},
            {"time": (11.2*1)+7, "pos": [64, 64]},
            {"time": (11.2*1)+8.4, "pos": [320, 64]},
            {"time": (11.2*1)+8.4, "pos": [64, 320]},
            {"time": (11.2*1)+9.8, "pos": [320, 320]},
            {"time": (11.2*1)+11.2, "pos": [64, 320]},
            {"time": (11.2*2), "pos": [64, 64]},
            {"time": (11.2*2)+1.4, "pos": [320, 64]},
            {"time": (11.2*2)+1.4, "pos": [64, 64]},
            {"time": (11.2*2)+2.8, "pos": [320, 64]},
            {"time": (11.2*2)+2.8, "pos": [64, 320]},
            {"time": (11.2*2)+4.2, "pos": [320, 320]},
            {"time": (11.2*2)+4.2, "pos": [64, 320]},
            {"time": (11.2*2)+5.6, "pos": [320, 320]},
            {"time": (11.2*2)+5.6, "pos": [64, 64]},
            {"time": (11.2*2)+7, "pos": [320, 64]},
            {"time": (11.2*2)+7, "pos": [64, 64]},
            {"time": (11.2*2)+8.4, "pos": [320, 64]},
            {"time": (11.2*2)+8.4, "pos": [64, 320]},
            {"time": (11.2*2)+9.8, "pos": [320, 320]},
            {"time": (11.2*2)+9.8, "pos": [64, 320]},
            {"time": (11.2*2)+11.2, "pos": [320, 320]},
            {"time": 1e100, "pos": [0, 0]}
        ],
        "guns": [
            {"time": 0, "gun": "none"},
            {"time": (11.2*1), "gun": "classic"},
            {"time": (11.2*1)+9.8, "gun": "none"},
            {"time": (11.2*2), "gun": "pico"},
            {"time": 35.575, "gun": "buckshot"},
            {"time": 36.350, "gun": "pico"},
            {"time": 1e100, "gun": "none"}
        ],
        "subtitle": [
            {"time": 0, "subtitle": ""},
            {"time": 22.592, "subtitle": "BR- BR- BR- BR- BR- BR- BR-"},
            {"time": 23.149, "subtitle": "BRUISES ON MY NECK"},
            {"time": 23.850, "subtitle": "NE- NE- NE- NE-"},
            {"time": 24.500, "subtitle": "JUST A DOLL OF FLESH"},
            {"time": 25.350, "subtitle": "FLE- FLE- FLE- FLE-"},
            {"time": 25.950, "subtitle": "YOU'LL FIND MY SMOKING BODY"},
            {"time": 27.000, "subtitle": "HUNG IN WIRES OVERHEAD"},
            {"time": 28.000, "subtitle": "HEA- HEA- HEA- HEA-"},
            {"time": 28.900, "subtitle": "AT UR BARK AND COLLAR"},
            {"time": 29.900, "subtitle": "JUST FORGET"},
            {"time": 30.400, "subtitle": "I'M SOMEONES DAUGHTER"},
            {"time": 31.000, "subtitle": "-TER -TER"},
            {"time": 31.500, "subtitle": "I CAN'T EVER FUCK IT UP"},
            {"time": 32.650, "subtitle": "IF I DONT EVER EVEN BOTHER"},
            {"time": 33.900, "subtitle": "-ER -ER -ER"},
            {"time": 34.500, "subtitle": "I LOVE TO TAKE IT SLOW"},
            {"time": 35.575, "subtitle": "ROLL"},
            {"time": 35.750, "subtitle": "ROLL THE"},
            {"time": 36.000, "subtitle": "ROLL THE KA"},
            {"time": 36.250, "subtitle": "ROLL THE KATA"},
            {"time": 36.350, "subtitle": "ROLL THE KATAMARI"},
            {"time": 36.700, "subtitle": ""},
            {"time": 37.000, "subtitle": "YEAH I GOT IT IN MY CLUTCH"},
            {"time": 38.100, "subtitle": "I GOT THE"},
            {"time": 38.750, "subtitle": "TRA"},
            {"time": 39.050, "subtitle": "TRACKER"},
            {"time": 39.150, "subtitle": "TRACKER ON"},
            {"time": 39.300, "subtitle": "TRACKER ON ME"},
            {"time": 39.550, "subtitle": ""},
            {"time": 39.750, "subtitle": "I'M ON THE INTERNET"},
            {"time": 40.822, "subtitle": "I BUFFER"},
            {"time": 41.212, "subtitle": "USE YOUR ADBLOCK ON ME"},
            {"time": 42.334, "subtitle": "I'M ON THE INTERNET"},
            {"time": 43.500, "subtitle": "I"},
            {"time": 43.725, "subtitle": "I GET"},
            {"time": 43.850, "subtitle": "I GET TO"},
            {"time": 44.075, "subtitle": "I GET TO CHOOSE"},
            {"time": 44.275, "subtitle": "I GET TO CHOOSE<br>JUST"},
            {"time": 44.450, "subtitle": "I GET TO CHOOSE<br>JUST WHAT"},
            {"time": 44.625, "subtitle": "I GET TO CHOOSE<br>JUST WHAT I"},
            {"time": 44.800, "subtitle": "I GET TO CHOOSE<br>JUST WHAT I WANNA"},
            {"time": 45.400, "subtitle": ""},

            {"time": 55.500, "subtitle": "I- I- I- I- I- I-"},
            {"time": 56.400, "subtitle": "DSI AT A LIMITED RATE"},
            {"time": 57.688, "subtitle": "IT'S A HELL OF A DRUG"},
            {"time": 58.215, "subtitle": "AND IT'S A HELL OF A RAGE"},
            {"time": 59.000, "subtitle": "GOT A CRT"},
            {"time": 59.782, "subtitle": "AND ONLY SEVEN MORE DAYS"},
            {"time": 60.509, "subtitle": "TILL I DROP COLD DEAD"},
            {"time": 61.220, "subtitle": "FROM THE CLOT IN MY BRAIN"},

            // Unfinished, retime lines 1-4
            {"time": 62.000, "subtitle": "I'M MADE OF DEAD MEAT"},
            {"time": 63.000, "subtitle": "AND I GOT NO TASTE"},
            {"time": 64.000, "subtitle": "AND I WONT LET UP TILL I GET MY WAY"},
            {"time": 64.500, "subtitle": "GOT SHARP WIDE EYES AND I BOUNCE IN PLACE"},
            {"time": 66.000, "subtitle": "GOT A BIG SHARP KNIFE IT'S MY OWN X RAY"},
            {"time": 67.200, "subtitle": "AAAAAAAAAAAAAAAAA"},

            {"time": 67.592, "subtitle": "BR- BR- BR- BR- BR- BR- BR-"},
            {"time": 68.149, "subtitle": "BRUISES ON MY NECK"},
            {"time": 68.850, "subtitle": "NE- NE- NE- NE-"},
            {"time": 69.500, "subtitle": "JUST A DOLL OF FLESH"},
            {"time": 70.350, "subtitle": "FLE- FLE- FLE- FLE-"},
            {"time": 70.950, "subtitle": "YOU'LL FIND MY SMOKING BODY"},
            {"time": 72.000, "subtitle": "HUNG IN WIRES OVERHEAD"},
            {"time": 73.000, "subtitle": "HEA- HEA- HEA- HEA-"},
            {"time": 73.900, "subtitle": "AT UR BARK AND COLLAR"},
            {"time": 74.900, "subtitle": "JUST FORGET"},
            {"time": 75.400, "subtitle": "I'M SOMEONES DAUGHTER"},
            {"time": 76.000, "subtitle": "-TER -TER"},
            {"time": 76.500, "subtitle": "I CAN'T EVER FUCK IT UP"},
            {"time": 77.650, "subtitle": "IF I DONT EVER EVEN BOTHER"},
            {"time": 78.900, "subtitle": "-ER -ER -ER"},
            {"time": 79.500, "subtitle": "I LOVE TO TAKE IT SLOW"},
            {"time": 80.575, "subtitle": "ROLL"},
            {"time": 80.750, "subtitle": "ROLL THE"},
            {"time": 81.000, "subtitle": "ROLL THE KA"},
            {"time": 81.250, "subtitle": "ROLL THE KATA"},
            {"time": 81.350, "subtitle": "ROLL THE KATAMARI"},
            {"time": 81.700, "subtitle": ""},
            {"time": 82.000, "subtitle": "YEAH I GOT IT IN MY CLUTCH"},
            {"time": 83.100, "subtitle": "I GOT THE"},
            {"time": 83.750, "subtitle": "TRA"},
            {"time": 84.050, "subtitle": "TRACKER"},
            {"time": 84.150, "subtitle": "TRACKER ON"},
            {"time": 84.300, "subtitle": "TRACKER ON ME"},
            {"time": 84.550, "subtitle": ""},
            {"time": 84.750, "subtitle": "I'M ON THE INTERNET"},
            {"time": 85.822, "subtitle": "I BUFFER"},
            {"time": 85.212, "subtitle": "USE YOUR ADBLOCK ON ME"},
            {"time": 87.334, "subtitle": "I'M ON THE INTERNET"},
            {"time": 88.500, "subtitle": "I"},
            {"time": 88.725, "subtitle": "I GET"},
            {"time": 88.850, "subtitle": "I GET TO"},
            {"time": 89.075, "subtitle": "I GET TO CHOOSE"},
            {"time": 89.275, "subtitle": "I GET TO CHOOSE<br>JUST"},
            {"time": 89.450, "subtitle": "I GET TO CHOOSE<br>JUST WHAT"},
            {"time": 89.625, "subtitle": "I GET TO CHOOSE<br>JUST WHAT I"},
            {"time": 89.800, "subtitle": "I GET TO CHOOSE<br>JUST WHAT I WANNA"},
            {"time": 90.400, "subtitle": ""},

            {"time": 96.000, "subtitle": "HEY LETS GO YOU'RE ON A ROLL"},
            {"time": 97.250, "subtitle": "GO ON LOOSE YOUR SELF CONTROL"},
            {"time": 98.750, "subtitle": "GOT NO PLACE I'D RATHER GO"},

            // DUET!
            {"time": 99.900, "subtitle": "<p style=\"color: cyan\">- - - I LOST MY MIND</p><p>CAUSE I LOST MY MIND</p>"},
            {"time": 100.760, "subtitle": "<p style=\"color: cyan\">IN LATE SEPTEMBER</p><p>IN LATE SEPTEMBER</p>"},
            
            // Unfinished, retime lines
            {"time": 102.760, "subtitle": "<p style=\"color: cyan\">DIAL NUMBERS WATCH YOUR TONE</p><p>DIAL NUMBERS WATCH YOUR TONE</p>"},
            {"time": 104.760, "subtitle": "<p style=\"color: cyan\">CLOCKWORK WIND UP ALL ALONE</p><p>CLOCKWORK WIND UP ALL ALONE</p>"},
            {"time": 105.760, "subtitle": "<p style=\"color: cyan\">THE MORE YOU STOP THE MORE I GO</p><p>THE MORE YOU STOP THE MORE I GO</p>"},
            {"time": 106.760, "subtitle": "<p style=\"color: cyan\">DO YOUR BEST I'LL DO ONE BETTER</p><p>DO YOUR BEST I'LL DO ONE BETTER</p>"},
            
            {"time": 107.760, "subtitle": "<p style=\"color: cyan\">YOU SAY WILL WHEN I SAY WONT</p><p>YOU SAY WILL WHEN I SAY WONT</p>"},
            {"time": 108.760, "subtitle": "<p style=\"color: cyan\">YOU SAY DO BUT I SAY DON'T</p><p>YOU SAY DO BUT I SAY DON'T</p>"},
            {"time": 110.000, "subtitle": "<p style=\"color: cyan\">I'M RUNNING OUT OF WAYS TO COPE</p><p>I'M RUNNING OUT OF WAYS TO COPE</p>"},
            {"time": 111.322, "subtitle": "<p style=\"color: cyan\">SO I BITE THE HAND THAT FEEDS ME</p><p>SO I BITE THE HAND THAT FEEDS ME</p>"},
            {"time": 112.515, "subtitle": "<p style=\"color: cyan\">LOOSE MY</p><p>LOOSE MY</p>"},
            // DUET END!

            {"time": 112.939, "subtitle": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
            {"time": 116.878, "subtitle": "WHAT THE FUCK IS WRONG WITH YOU"},
            {"time": 119.300, "subtitle": ""},
            {"time": 120.100, "subtitle": "YOU FUCKING ANIMAL"},
            {"time": 121.617, "subtitle": "YOU PIECE OF SHIT"},
            {"time": 122.800, "subtitle": "LITTLE TINY DICK LICKER"},
            {"time": 124.638, "subtitle": "FUCKING ASSHOLE"},
            {"time": 125.636, "subtitle": "FUCKING I-"},
            {"time": 127.500, "subtitle": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
            {"time": 130.500, "subtitle": ""},

            {"time": 152.447, "subtitle": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
            {"time": 154.000, "subtitle": ""},

            {"time": 155.636, "subtitle": "YOU LITTLE"},
            {"time": 156.506, "subtitle": ""},
            {"time": 157.105, "subtitle": "FUCKER"},

            {"time": 1e100, "subtitle": ""}
        ]
    }
}